"""add verdict_cache table

Revision ID: c1e782f9e61f
Revises: e270a0ee5591
Create Date: 2026-03-15 09:30:23.656457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e782f9e61f'
down_revision: Union[str, None] = 'e270a0ee5591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verdict_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercise_key', sa.String(length=255), nullable=False),
    sa.Column('user_answer', sa.String(length=500), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_key', 'user_answer')
    )
    op.create_index('ix_verdict_cache_lookup', 'verdict_cache', ['exercise_key', 'user_answer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verdict_cache_lookup', table_name='verdict_cache')
    op.drop_table('verdict_cache')
    # ### end Alembic commands ###
