"""add progress and srs_cards tables

Revision ID: e270a0ee5591
Revises: 46f5b65a1efd
Create Date: 2026-03-14 19:20:12.084118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e270a0ee5591'
down_revision: Union[str, None] = '46f5b65a1efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('srs_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.String(length=100), nullable=False),
    sa.Column('skill_type', sa.String(length=50), nullable=False),
    sa.Column('due', sa.DateTime(), nullable=False),
    sa.Column('card_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', 'skill_type')
    )
    op.create_index('ix_srs_cards_user_due', 'srs_cards', ['user_id', 'due'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_section', sa.String(length=50), nullable=False),
    sa.Column('current_unit', sa.String(length=50), nullable=False),
    sa.Column('current_lesson', sa.String(length=50), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('lessons_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checkpoints_passed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lesson_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('badges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('streak_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('daily_activity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress')
    op.drop_index('ix_srs_cards_user_due', table_name='srs_cards')
    op.drop_table('srs_cards')
    # ### end Alembic commands ###
